require:
- rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'spec/spec_helper.rb'
  - 'coverage/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  # Optional: exclude the test folder from this check
  Exclude:
  - 'spec/**/*'

# You might also find 'AbcSize' starts failing as methods get complex.
# You can increase that here too if needed:
Metrics/AbcSize:
  Max: 20
