require:
- rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'spec/spec_helper.rb'
  - 'coverage/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
