require 'spec_helper'

RSpec.describe 'NotifyPit' do
  def post_json(path, hash)
    post path, hash.to_json, { 'CONTENT_TYPE' => 'application/json' }
  end

  before(:each) do
    delete '/mocker/reset'
  end

  describe 'Smoke Test Flow (Auto-Reply)' do
    it 'detects the "Go" trigger (Inbox) and places credentials in the Outbox' do
      # 1. INBOX: Send "Go"
      trigger_id = 'go_template_id'
      post_json '/v2/notifications/sms', {
        phone_number: '07700900000',
        template_id: trigger_id,
        personalisation: { content: 'Go' }
      }

      expect(last_response.status).to eq(201)

      # 2. OUTBOX: Check for the Reply
      get '/v2/received-text-messages'

      expect(last_response.status).to eq(200)
      json = JSON.parse(last_response.body)
      messages = json['received_text_messages']

      expect(messages).not_to be_empty
      latest = messages.last

      # It should contain the credentials generated by add_message
      expect(latest['content']).to include('Your GovWifi details are:')
      expect(latest['content']).to match(/Username:\n[a-z]{6}/)
    end
  end

  describe 'Standard Notify API' do
    it 'captures generic outbound SMS without triggering a reply' do
      # INBOX: Send generic message
      post_json '/v2/notifications/sms', {
        phone_number: '07700900000',
        template_id: 'generic-template-id'
      }

      expect(last_response.status).to eq(201)

      # OUTBOX: Should be empty (No reply generated)
      get '/v2/received-text-messages'
      messages = JSON.parse(last_response.body)['received_text_messages']
      expect(messages).to be_empty

      # INBOX VERIFICATION: Should contain our sent message
      get '/mocker/messages'
      sent = JSON.parse(last_response.body)
      expect(sent.length).to eq(1)
      expect(sent.first['template_id']).to eq('generic-template-id')
    end

    it 'captures Email' do
      post_json '/v2/notifications/email', {
        email_address: 'test@example.com',
        template_id: 'email-temp',
        personalisation: { 'name' => 'Test' }
      }

      expect(last_response.status).to eq(201)
      resp = JSON.parse(last_response.body)
      expect(resp['id']).not_to be_nil
    end
  end

  describe 'Notification Retrieval' do
    it 'retrieves a specific notification by ID' do
      # 1. Create a notification first
      post_json '/v2/notifications/sms', {
        phone_number: '07700900000',
        template_id: 'retrieval-test'
      }
      expect(last_response.status).to eq(201)
      created_id = JSON.parse(last_response.body)['id']

      # 2. Fetch it by ID
      get "/v2/notifications/#{created_id}"

      expect(last_response.status).to eq(200)
      json = JSON.parse(last_response.body)
      expect(json['id']).to eq(created_id)
      expect(json['template_id']).to eq('retrieval-test')
      expect(json['body']).to include('Your GovWifi details are:') # Checks generator logic
    end

    it 'returns 404 for a non-existent notification ID' do
      get '/v2/notifications/caa1584b-0000-0000-0000-123456789abc'
      expect(last_response.status).to eq(404)
    end
  end

  describe 'Management API' do
    it 'allows manual injection of messages into the Outbox' do
      post_json '/mocker/inbound-sms', { content: 'Manually Injected', phone_number: '07700900001' }

      get '/v2/received-text-messages'
      msgs = JSON.parse(last_response.body)['received_text_messages']

      expect(msgs.length).to eq(1)
      expect(msgs.first['content']).to eq('Manually Injected')
    end

    it 'resets the data stores' do
      post_json '/v2/notifications/sms', { phone_number: '07700', template_id: '1' }
      delete '/mocker/reset'

      get '/mocker/messages'
      expect(JSON.parse(last_response.body).length).to eq(0)
    end

    it 'provides a health check' do
      get '/health'
      expect(last_response.status).to eq(200)
    end

    it 'allows polling of received text messages' do
      post_json '/mocker/inbound-sms', { content: 'test 1', phone_number: '07700900001' }
      post_json '/mocker/inbound-sms', { content: 'test 2', phone_number: '07700900002' }
      get '/v2/received-text-messages'

      expect(last_response.status).to eq(200)
      msgs = JSON.parse(last_response.body)['received_text_messages']

      expect(msgs).not_to be_empty
      expect(msgs.first['content']).to eq('test 1')
      expect(msgs.length).to eq(2)
    end
  end
end
